# Workflow Configuration

# General workflow settings
workflow:
  name: "Primitive State Segmentation and Clustering"
  description: "Standard ML workflow for processing and training on input data."
  appliance_name: "microwave" 

# Step-specific configurations
steps:
  data_loader:
    enabled: false
    input_folder: "input"
    supported_formats: [".npy", ".txt"]
    
  data_processor:
    enabled: false
    normalization: true
    save_figures: true

  wavelet_separation:
    enabled: false
    is_shape_dtw: false
    plot_count: 0

  feature_extract:
    enabled: false
    data_path: "D:\\KnowledgeDatabase\\ComputerSecience\\PROJ_NILM\\PSLG-NILM\\data\\dishwasher\\data_fusion.npy"
    seq_len_path: "D:\\KnowledgeDatabase\\ComputerSecience\\PROJ_NILM\\PSLG-NILM\\data\\dishwasher\\seq_length_fusion.npy"
    model_name: "bilstm_ae"
    latent_dim: 64
    epochs: 50
    batch_size: 32
    learning_rate: 0.001
    patience: 5
    attention_size: 32
  
  time_clustering:
    enabled: true
    data_path: "D:\\KnowledgeDatabase\\ComputerSecience\\PROJ_NILM\\PSLG-NILM\\input\\microwave\\data_fusion.npy"
    feature_path: "D:\\KnowledgeDatabase\\ComputerSecience\\PROJ_NILM\\PSLG-NILM\\input\\microwave\\bilstm_ae_attention_v2_features_cleaned_power_64_dim.npy"
    seq_len_path: "D:\\KnowledgeDatabase\\ComputerSecience\\PROJ_NILM\\PSLG-NILM\\input\\microwave\\seq_length_fusion.npy"
    cluster_method: "dbscan-scan"  # dbscan / dbscan-scan / kmeans / kmeans-scan
    method_specific:
      dbscan:
        eps: 1.2
        min_pts: 20
        metric: "euclidean"
      dbscan-scan:
        min_eps: 0.2
        max_eps: 2.0
        eps_gap: 0.05
        min_pts: 20
        metric: "euclidean"
      kmeans:
        n_clusters: 4
        random_state: 42
        n_init: 30
        max_iter: 300
      kmeans-scan:
        min_cluster: 2
        max_cluster: 8
        random_state: 42
        n_init: 30
        max_iter: 300
    normalization_method: "zscore"
    col_index: 2  # the index of the feature column to be used for clustering (0-based)
    visualization_specific:
      enabled: true
      visualize_noise: true
      language: "en"  # zh / en
      cluster_stack_count: 50
  

# Model hyperparameters
models:
  DummyModel:
    learning_rate: 0.01
    epochs: 10
    batch_size: 32
