# Workflow Configuration

# General workflow settings
workflow:
  name: "Primitive State Segmentation and Clustering"
  description: "Standard ML workflow for processing and training on input data."
  appliance_name: "kettle" 
  resume: true #有done会跳过已执行的step
  sequence_id: "20260513_220235"

# Step-specific configurations
steps:
  extract_active_data:
    enabled: true
    input_file: "input/kettle.csv"
    power_threshold: 1.0
    min_duration_seconds: 30
    context_seconds: 120
    alpha: 0.2
    min_stop_time: 5
    sample_rate: 10
    set_input_root: true

  data_processor:
    enabled: false
    normalization: true
    save_figures: true

  wavelet_separation:
    enabled: true
    is_shape_dtw: false
    plot_count: 0

  feature_extract:
    enabled: false
    data_path: ""
    seq_len_path: ""
    model_name: "bilstm_ae"
    latent_dim: 64
    epochs: 50
    batch_size: 32
    learning_rate: 0.001
    patience: 5
    attention_size: 32
  
  time_clustering:
    enabled: false
    data_path: ""
    feature_path: ""
    seq_len_path: ""
    cluster_method: "kmeans-scan"  # dbscan / dbscan-scan / kmeans / kmeans-scan
    method_specific:
      dbscan:
        eps: 1.25
        min_pts: 20
        metric: "euclidean"
      dbscan-scan:
        min_eps: 0.02
        max_eps: 2.0
        eps_gap: 0.02
        min_pts: 20
        metric: "euclidean"
      kmeans:
        n_clusters: 4
        random_state: 42
        n_init: 30
        max_iter: 300
      kmeans-scan:
        min_cluster: 2
        max_cluster: 8
        random_state: 42
        n_init: 30
        max_iter: 300
    normalization_method: "zscore"
    col_index: 2  # the index of the feature column to be used for clustering (0-based)
    visualization_specific:
      enabled: true
      visualize_noise: true
      language: "en"  # zh / en
      cluster_stack_count: 50
  

# Model hyperparameters
models:
  DummyModel:
    learning_rate: 0.01
    epochs: 10
    batch_size: 32
